# Netlify configuration file
[build]
  publish = "."
  command = ""

# Environment variables for build
[build.environment]
  # Google Maps API key wordt ingesteld via Netlify dashboard

# Headers voor security
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://unpkg.com https://maps.googleapis.com https://maps.gstatic.com;
      style-src 'self' 'unsafe-inline' https://unpkg.com https://fonts.googleapis.com;
      img-src 'self' data: https://*.googleapis.com https://*.gstatic.com https://images.unsplash.com https://*.tile.openstreetmap.org;
      connect-src 'self' https://maps.googleapis.com https://*.tile.openstreetmap.org;
      font-src 'self' https://fonts.gstatic.com;
      frame-src 'none';
    """
    # Andere security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirects voor clean URLs
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# 404 error handling
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
